[external_resources.github_releases.superpowers]
repository = "obra/superpowers"
tag = "v6.3.0"
sha256 = "2933703111f44dd1ae0234372cd2a924afb372a682fe3d9acdb6497231213fcb"

[external_resources.github_releases.mattpocock_skills]
repository = "mattpocock/skills"
tag = "v1.2.3"
sha256 = "238fac54d0f53d3e2d0501c1b38c9c0e4e9bc26f6b057b53a7328ea15d43b66f"

[external_resources.github_release_assets.pi_distribution]
repository = "ningw42/pi-distribution"
tag = "v26.08.17"

[external_resources.github_release_assets.pi_distribution.assets.windows_x64]
name = "pi-distribution-{tag}-windows-x64.tgz"
sha256 = "07817d26224d0fd6bbdf2801c213a771190cff300b4a1bf531fa27c5589497c8"

[external_resources.github_release_assets.pi_distribution.assets.windows_arm64]
name = "pi-distribution-{tag}-windows-arm64.tgz"
sha256 = "3daad3bc4487f712ae1756e32c2abb4dfad80c694127250d26fd3c4dcf53cf74"
