[external_resources.github_releases.superpowers]
repository = "obra/superpowers"
tag = "v6.3.0"
sha256 = "2933703111f44dd1ae0234372cd2a924afb372a682fe3d9acdb6497231213fcb"

[external_resources.github_releases.mattpocock_skills]
repository = "mattpocock/skills"
tag = "v1.2.3"
sha256 = "238fac54d0f53d3e2d0501c1b38c9c0e4e9bc26f6b057b53a7328ea15d43b66f"

[external_resources.github_release_assets.pi_distribution]
repository = "ningw42/pi-distribution"
tag = "v26.08.28"

[external_resources.github_release_assets.pi_distribution.assets.windows_x64]
name = "pi-distribution-{tag}-windows-x64.tgz"
sha256 = "71525f185d89f91bd73d9bf4b4fe90f44b2d159ae220aa6880ee30596a3002b7"

[external_resources.github_release_assets.pi_distribution.assets.windows_arm64]
name = "pi-distribution-{tag}-windows-arm64.tgz"
sha256 = "e3bfd118513d1abfa2fef695e91b8f9f3a6c0c697dd8a333c357d80ea7091afb"
