onboarding = false

[keys]
prefix = "ctrl+b"
goto = "prefix+g"
new_tab = ["prefix+c", "alt+n"]
next_agent = "alt+shift+down"
next_tab = ["prefix+n", "alt+right"]
next_workspace = "alt+down"
previous_agent = "alt+shift+up"
previous_tab = ["prefix+p", "alt+left"]
previous_workspace = "alt+up"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[terminal]
default_shell = "pwsh"
new_cwd = "follow"

[theme]
name = "catppuccin"
auto_switch = false
light_name = "catppuccin-latte"
dark_name = "catppuccin"

[ui]
pane_scrollbars = false

[update]
version_check = false
manifest_check = true
