[keys]
prefix = "ctrl+b"
goto = "prefix+g"
new_tab = ["prefix+c", "alt+n"]
next_tab = ["prefix+n", "alt+right"]
previous_tab = ["prefix+p", "alt+left"]

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[terminal]
default_shell = "pwsh"
new_cwd = "follow"

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"

[update]
version_check = false
manifest_check = true
