return {
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    branch = "main",
    version = false,
  },

  {
    "nvim-treesitter/nvim-treesitter",
    branch = "main",
    version = false, -- last release is way too old and doesn't work on Windows
    build = ":TSUpdate",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
      "nvim-treesitter/nvim-treesitter-context",
    },
    opts = {
      languages = {
        "bash",
        "beancount",
        "c",
        "csv",
        "diff",
        "dockerfile",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "gotmpl",
        "gpg",
        "html",
        "ini",
        "javascript",
        "jinja",
        "jinja_inline",
        "jq",
        "json",
        "jsonc",
        "kdl",
        "latex",
        "kusto",
        "lua",
        "luadoc",
        "luap",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "powershell",
        "proto",
        "python",
        "query",
        "regex",
        "ron",
        "rust",
        "sql",
        "ssh_config",
        "tera",
        "toml",
        "typst",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
    },
    config = function(_, opts)
      require("nvim-treesitter").setup({
        install_dir = vim.fn.stdpath("data") .. "/site"
      })
      require("nvim-treesitter").install(opts.languages)
    end,
  },
}
